//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MES_Tablet_PC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.10.19:8080/axis/RfEntry.jws", ConfigurationName="ServiceReference1.RfEntry")]
    public interface RfEntry {
        
        // CODEGEN: 消息 mainRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        MES_Tablet_PC.ServiceReference1.mainResponse main(MES_Tablet_PC.ServiceReference1.mainRequest request);
        
        // CODEGEN: 消息 GetDataTableCRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.GetDataTableCResponse GetDataTableC(MES_Tablet_PC.ServiceReference1.GetDataTableCRequest request);
        
        // CODEGEN: 消息 downloadFileRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.downloadFileResponse downloadFile(MES_Tablet_PC.ServiceReference1.downloadFileRequest request);
        
        // CODEGEN: 消息 HelloRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.HelloResponse Hello(MES_Tablet_PC.ServiceReference1.HelloRequest request);
        
        // CODEGEN: 消息 WorkRegisterRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.WorkRegisterResponse WorkRegister(MES_Tablet_PC.ServiceReference1.WorkRegisterRequest request);
        
        // CODEGEN: 消息 verifyUserRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.verifyUserResponse verifyUser(MES_Tablet_PC.ServiceReference1.verifyUserRequest request);
        
        // CODEGEN: 消息 getDataTableRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.getDataTableResponse getDataTable(MES_Tablet_PC.ServiceReference1.getDataTableRequest request);
        
        // CODEGEN: 消息 CheckRoutePassedRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.CheckRoutePassedResponse CheckRoutePassed(MES_Tablet_PC.ServiceReference1.CheckRoutePassedRequest request);
        
        // CODEGEN: 消息 UpdateTerminalResRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.UpdateTerminalResResponse UpdateTerminalRes(MES_Tablet_PC.ServiceReference1.UpdateTerminalResRequest request);
        
        // CODEGEN: 消息 getColumnStringAllRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.getColumnStringAllResponse getColumnStringAll(MES_Tablet_PC.ServiceReference1.getColumnStringAllRequest request);
        
        // CODEGEN: 消息 getColumnStringsRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.getColumnStringsResponse getColumnStrings(MES_Tablet_PC.ServiceReference1.getColumnStringsRequest request);
        
        // CODEGEN: 消息 CheckUserAndResourcePassedRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedResponse CheckUserAndResourcePassed(MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedRequest request);
        
        // CODEGEN: 消息 TerminalRegisterRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.TerminalRegisterResponse TerminalRegister(MES_Tablet_PC.ServiceReference1.TerminalRegisterRequest request);
        
        // CODEGEN: 消息 Get_Table_DateRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.Get_Table_DateResponse Get_Table_Date(MES_Tablet_PC.ServiceReference1.Get_Table_DateRequest request);
        
        // CODEGEN: 消息 getColumnStringRequest 的包装命名空间(http://DefaultNamespace)以后生成的消息协定与默认值(http://192.168.10.19:8080/axis/RfEntry.jws)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Vector))]
        MES_Tablet_PC.ServiceReference1.getColumnStringResponse getColumnString(MES_Tablet_PC.ServiceReference1.getColumnStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="main", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class mainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] arg;
        
        public mainRequest() {
        }
        
        public mainRequest(string[] arg) {
            this.arg = arg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mainResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class mainResponse {
        
        public mainResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://data")]
    public partial class DataTable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object columnsField;
        
        private object[] entityRowsField;
        
        private bool readOnlyField;
        
        private object rowsField;
        
        private string tableNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] entityRows {
            get {
                return this.entityRowsField;
            }
            set {
                this.entityRowsField = value;
                this.RaisePropertyChanged("entityRows");
            }
        }
        
        /// <remarks/>
        public bool readOnly {
            get {
                return this.readOnlyField;
            }
            set {
                this.readOnlyField = value;
                this.RaisePropertyChanged("readOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("rows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("tableName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Vector : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemField;
        
        /// <remarks/>
        public object[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataTableC", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class GetDataTableCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public GetDataTableCRequest() {
        }
        
        public GetDataTableCRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataTableCResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class GetDataTableCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public MES_Tablet_PC.ServiceReference1.DataTable GetDataTableCReturn;
        
        public GetDataTableCResponse() {
        }
        
        public GetDataTableCResponse(MES_Tablet_PC.ServiceReference1.DataTable GetDataTableCReturn) {
            this.GetDataTableCReturn = GetDataTableCReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFile", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class downloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string colname;
        
        public downloadFileRequest() {
        }
        
        public downloadFileRequest(string sql, string colname) {
            this.sql = sql;
            this.colname = colname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadFileResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class downloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] downloadFileReturn;
        
        public downloadFileResponse() {
        }
        
        public downloadFileResponse(byte[] downloadFileReturn) {
            this.downloadFileReturn = downloadFileReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Hello", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class HelloRequest {
        
        public HelloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string HelloReturn;
        
        public HelloResponse() {
        }
        
        public HelloResponse(string HelloReturn) {
            this.HelloReturn = HelloReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkRegister", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class WorkRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string iMAC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string iCardCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string iFlag;
        
        public WorkRegisterRequest() {
        }
        
        public WorkRegisterRequest(string iMAC, string iCardCode, string iFlag) {
            this.iMAC = iMAC;
            this.iCardCode = iCardCode;
            this.iFlag = iFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkRegisterResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class WorkRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WorkRegisterReturn;
        
        public WorkRegisterResponse() {
        }
        
        public WorkRegisterResponse(string WorkRegisterReturn) {
            this.WorkRegisterReturn = WorkRegisterReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyUser", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class verifyUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public verifyUserRequest() {
        }
        
        public verifyUserRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyUserResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class verifyUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string verifyUserReturn;
        
        public verifyUserResponse() {
        }
        
        public verifyUserResponse(string verifyUserReturn) {
            this.verifyUserReturn = verifyUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataTable", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getDataTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public getDataTableRequest() {
        }
        
        public getDataTableRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataTableResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class getDataTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] getDataTableReturn;
        
        public getDataTableResponse() {
        }
        
        public getDataTableResponse(string[] getDataTableReturn) {
            this.getDataTableReturn = getDataTableReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRoutePassed", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class CheckRoutePassedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Sn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Resource;
        
        public CheckRoutePassedRequest() {
        }
        
        public CheckRoutePassedRequest(string Sn, string Resource) {
            this.Sn = Sn;
            this.Resource = Resource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRoutePassedResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class CheckRoutePassedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CheckRoutePassedReturn;
        
        public CheckRoutePassedResponse() {
        }
        
        public CheckRoutePassedResponse(string CheckRoutePassedReturn) {
            this.CheckRoutePassedReturn = CheckRoutePassedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTerminalRes", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class UpdateTerminalResRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string iMAC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string iUserid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string iPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string iLineCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string iResCode;
        
        public UpdateTerminalResRequest() {
        }
        
        public UpdateTerminalResRequest(string iMAC, string iUserid, string iPassword, string iLineCode, string iResCode) {
            this.iMAC = iMAC;
            this.iUserid = iUserid;
            this.iPassword = iPassword;
            this.iLineCode = iLineCode;
            this.iResCode = iResCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTerminalResResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class UpdateTerminalResResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string UpdateTerminalResReturn;
        
        public UpdateTerminalResResponse() {
        }
        
        public UpdateTerminalResResponse(string UpdateTerminalResReturn) {
            this.UpdateTerminalResReturn = UpdateTerminalResReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnStringAll", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getColumnStringAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public getColumnStringAllRequest() {
        }
        
        public getColumnStringAllRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnStringAllResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class getColumnStringAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getColumnStringAllReturn;
        
        public getColumnStringAllResponse() {
        }
        
        public getColumnStringAllResponse(object[] getColumnStringAllReturn) {
            this.getColumnStringAllReturn = getColumnStringAllReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnStrings", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getColumnStringsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public getColumnStringsRequest() {
        }
        
        public getColumnStringsRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnStringsResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class getColumnStringsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object[] getColumnStringsReturn;
        
        public getColumnStringsResponse() {
        }
        
        public getColumnStringsResponse(object[] getColumnStringsReturn) {
            this.getColumnStringsReturn = getColumnStringsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserAndResourcePassed", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class CheckUserAndResourcePassedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string iUserCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string iRescode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string iPassWord;
        
        public CheckUserAndResourcePassedRequest() {
        }
        
        public CheckUserAndResourcePassedRequest(string iUserCode, string iRescode, string iPassWord) {
            this.iUserCode = iUserCode;
            this.iRescode = iRescode;
            this.iPassWord = iPassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserAndResourcePassedResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class CheckUserAndResourcePassedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string CheckUserAndResourcePassedReturn;
        
        public CheckUserAndResourcePassedResponse() {
        }
        
        public CheckUserAndResourcePassedResponse(string CheckUserAndResourcePassedReturn) {
            this.CheckUserAndResourcePassedReturn = CheckUserAndResourcePassedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminalRegister", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class TerminalRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string iMAC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string iUserid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string iPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string iLineCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string iResCode;
        
        public TerminalRegisterRequest() {
        }
        
        public TerminalRegisterRequest(string iMAC, string iUserid, string iPassword, string iLineCode, string iResCode) {
            this.iMAC = iMAC;
            this.iUserid = iUserid;
            this.iPassword = iPassword;
            this.iLineCode = iLineCode;
            this.iResCode = iResCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TerminalRegisterResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class TerminalRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TerminalRegisterReturn;
        
        public TerminalRegisterResponse() {
        }
        
        public TerminalRegisterResponse(string TerminalRegisterReturn) {
            this.TerminalRegisterReturn = TerminalRegisterReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Table_Date", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class Get_Table_DateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string TableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int TableType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SqlString;
        
        public Get_Table_DateRequest() {
        }
        
        public Get_Table_DateRequest(string TableName, int TableType, string SqlString) {
            this.TableName = TableName;
            this.TableType = TableType;
            this.SqlString = SqlString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get_Table_DateResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class Get_Table_DateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Get_Table_DateReturn;
        
        public Get_Table_DateResponse() {
        }
        
        public Get_Table_DateResponse(string Get_Table_DateReturn) {
            this.Get_Table_DateReturn = Get_Table_DateReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnString", WrapperNamespace="http://DefaultNamespace", IsWrapped=true)]
    public partial class getColumnStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sql;
        
        public getColumnStringRequest() {
        }
        
        public getColumnStringRequest(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getColumnStringResponse", WrapperNamespace="http://192.168.10.19:8080/axis/RfEntry.jws", IsWrapped=true)]
    public partial class getColumnStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string getColumnStringReturn;
        
        public getColumnStringResponse() {
        }
        
        public getColumnStringResponse(string getColumnStringReturn) {
            this.getColumnStringReturn = getColumnStringReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RfEntryChannel : MES_Tablet_PC.ServiceReference1.RfEntry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RfEntryClient : System.ServiceModel.ClientBase<MES_Tablet_PC.ServiceReference1.RfEntry>, MES_Tablet_PC.ServiceReference1.RfEntry {
        
        public RfEntryClient() {
        }
        
        public RfEntryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RfEntryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RfEntryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RfEntryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.mainResponse MES_Tablet_PC.ServiceReference1.RfEntry.main(MES_Tablet_PC.ServiceReference1.mainRequest request) {
            return base.Channel.main(request);
        }
        
        public void main(string[] arg) {
            MES_Tablet_PC.ServiceReference1.mainRequest inValue = new MES_Tablet_PC.ServiceReference1.mainRequest();
            inValue.arg = arg;
            MES_Tablet_PC.ServiceReference1.mainResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).main(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.GetDataTableCResponse MES_Tablet_PC.ServiceReference1.RfEntry.GetDataTableC(MES_Tablet_PC.ServiceReference1.GetDataTableCRequest request) {
            return base.Channel.GetDataTableC(request);
        }
        
        public MES_Tablet_PC.ServiceReference1.DataTable GetDataTableC(string sql) {
            MES_Tablet_PC.ServiceReference1.GetDataTableCRequest inValue = new MES_Tablet_PC.ServiceReference1.GetDataTableCRequest();
            inValue.sql = sql;
            MES_Tablet_PC.ServiceReference1.GetDataTableCResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).GetDataTableC(inValue);
            return retVal.GetDataTableCReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.downloadFileResponse MES_Tablet_PC.ServiceReference1.RfEntry.downloadFile(MES_Tablet_PC.ServiceReference1.downloadFileRequest request) {
            return base.Channel.downloadFile(request);
        }
        
        public byte[] downloadFile(string sql, string colname) {
            MES_Tablet_PC.ServiceReference1.downloadFileRequest inValue = new MES_Tablet_PC.ServiceReference1.downloadFileRequest();
            inValue.sql = sql;
            inValue.colname = colname;
            MES_Tablet_PC.ServiceReference1.downloadFileResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).downloadFile(inValue);
            return retVal.downloadFileReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.HelloResponse MES_Tablet_PC.ServiceReference1.RfEntry.Hello(MES_Tablet_PC.ServiceReference1.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            MES_Tablet_PC.ServiceReference1.HelloRequest inValue = new MES_Tablet_PC.ServiceReference1.HelloRequest();
            MES_Tablet_PC.ServiceReference1.HelloResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).Hello(inValue);
            return retVal.HelloReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.WorkRegisterResponse MES_Tablet_PC.ServiceReference1.RfEntry.WorkRegister(MES_Tablet_PC.ServiceReference1.WorkRegisterRequest request) {
            return base.Channel.WorkRegister(request);
        }
        
        public string WorkRegister(string iMAC, string iCardCode, string iFlag) {
            MES_Tablet_PC.ServiceReference1.WorkRegisterRequest inValue = new MES_Tablet_PC.ServiceReference1.WorkRegisterRequest();
            inValue.iMAC = iMAC;
            inValue.iCardCode = iCardCode;
            inValue.iFlag = iFlag;
            MES_Tablet_PC.ServiceReference1.WorkRegisterResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).WorkRegister(inValue);
            return retVal.WorkRegisterReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.verifyUserResponse MES_Tablet_PC.ServiceReference1.RfEntry.verifyUser(MES_Tablet_PC.ServiceReference1.verifyUserRequest request) {
            return base.Channel.verifyUser(request);
        }
        
        public string verifyUser(string username, string password) {
            MES_Tablet_PC.ServiceReference1.verifyUserRequest inValue = new MES_Tablet_PC.ServiceReference1.verifyUserRequest();
            inValue.username = username;
            inValue.password = password;
            MES_Tablet_PC.ServiceReference1.verifyUserResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).verifyUser(inValue);
            return retVal.verifyUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.getDataTableResponse MES_Tablet_PC.ServiceReference1.RfEntry.getDataTable(MES_Tablet_PC.ServiceReference1.getDataTableRequest request) {
            return base.Channel.getDataTable(request);
        }
        
        public string[] getDataTable(string sql) {
            MES_Tablet_PC.ServiceReference1.getDataTableRequest inValue = new MES_Tablet_PC.ServiceReference1.getDataTableRequest();
            inValue.sql = sql;
            MES_Tablet_PC.ServiceReference1.getDataTableResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).getDataTable(inValue);
            return retVal.getDataTableReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.CheckRoutePassedResponse MES_Tablet_PC.ServiceReference1.RfEntry.CheckRoutePassed(MES_Tablet_PC.ServiceReference1.CheckRoutePassedRequest request) {
            return base.Channel.CheckRoutePassed(request);
        }
        
        public string CheckRoutePassed(string Sn, string Resource) {
            MES_Tablet_PC.ServiceReference1.CheckRoutePassedRequest inValue = new MES_Tablet_PC.ServiceReference1.CheckRoutePassedRequest();
            inValue.Sn = Sn;
            inValue.Resource = Resource;
            MES_Tablet_PC.ServiceReference1.CheckRoutePassedResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).CheckRoutePassed(inValue);
            return retVal.CheckRoutePassedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.UpdateTerminalResResponse MES_Tablet_PC.ServiceReference1.RfEntry.UpdateTerminalRes(MES_Tablet_PC.ServiceReference1.UpdateTerminalResRequest request) {
            return base.Channel.UpdateTerminalRes(request);
        }
        
        public string UpdateTerminalRes(string iMAC, string iUserid, string iPassword, string iLineCode, string iResCode) {
            MES_Tablet_PC.ServiceReference1.UpdateTerminalResRequest inValue = new MES_Tablet_PC.ServiceReference1.UpdateTerminalResRequest();
            inValue.iMAC = iMAC;
            inValue.iUserid = iUserid;
            inValue.iPassword = iPassword;
            inValue.iLineCode = iLineCode;
            inValue.iResCode = iResCode;
            MES_Tablet_PC.ServiceReference1.UpdateTerminalResResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).UpdateTerminalRes(inValue);
            return retVal.UpdateTerminalResReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.getColumnStringAllResponse MES_Tablet_PC.ServiceReference1.RfEntry.getColumnStringAll(MES_Tablet_PC.ServiceReference1.getColumnStringAllRequest request) {
            return base.Channel.getColumnStringAll(request);
        }
        
        public object[] getColumnStringAll(string sql) {
            MES_Tablet_PC.ServiceReference1.getColumnStringAllRequest inValue = new MES_Tablet_PC.ServiceReference1.getColumnStringAllRequest();
            inValue.sql = sql;
            MES_Tablet_PC.ServiceReference1.getColumnStringAllResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).getColumnStringAll(inValue);
            return retVal.getColumnStringAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.getColumnStringsResponse MES_Tablet_PC.ServiceReference1.RfEntry.getColumnStrings(MES_Tablet_PC.ServiceReference1.getColumnStringsRequest request) {
            return base.Channel.getColumnStrings(request);
        }
        
        public object[] getColumnStrings(string sql) {
            MES_Tablet_PC.ServiceReference1.getColumnStringsRequest inValue = new MES_Tablet_PC.ServiceReference1.getColumnStringsRequest();
            inValue.sql = sql;
            MES_Tablet_PC.ServiceReference1.getColumnStringsResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).getColumnStrings(inValue);
            return retVal.getColumnStringsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedResponse MES_Tablet_PC.ServiceReference1.RfEntry.CheckUserAndResourcePassed(MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedRequest request) {
            return base.Channel.CheckUserAndResourcePassed(request);
        }
        
        public string CheckUserAndResourcePassed(string iUserCode, string iRescode, string iPassWord) {
            MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedRequest inValue = new MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedRequest();
            inValue.iUserCode = iUserCode;
            inValue.iRescode = iRescode;
            inValue.iPassWord = iPassWord;
            MES_Tablet_PC.ServiceReference1.CheckUserAndResourcePassedResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).CheckUserAndResourcePassed(inValue);
            return retVal.CheckUserAndResourcePassedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.TerminalRegisterResponse MES_Tablet_PC.ServiceReference1.RfEntry.TerminalRegister(MES_Tablet_PC.ServiceReference1.TerminalRegisterRequest request) {
            return base.Channel.TerminalRegister(request);
        }
        
        public string TerminalRegister(string iMAC, string iUserid, string iPassword, string iLineCode, string iResCode) {
            MES_Tablet_PC.ServiceReference1.TerminalRegisterRequest inValue = new MES_Tablet_PC.ServiceReference1.TerminalRegisterRequest();
            inValue.iMAC = iMAC;
            inValue.iUserid = iUserid;
            inValue.iPassword = iPassword;
            inValue.iLineCode = iLineCode;
            inValue.iResCode = iResCode;
            MES_Tablet_PC.ServiceReference1.TerminalRegisterResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).TerminalRegister(inValue);
            return retVal.TerminalRegisterReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.Get_Table_DateResponse MES_Tablet_PC.ServiceReference1.RfEntry.Get_Table_Date(MES_Tablet_PC.ServiceReference1.Get_Table_DateRequest request) {
            return base.Channel.Get_Table_Date(request);
        }
        
        public string Get_Table_Date(string TableName, int TableType, string SqlString) {
            MES_Tablet_PC.ServiceReference1.Get_Table_DateRequest inValue = new MES_Tablet_PC.ServiceReference1.Get_Table_DateRequest();
            inValue.TableName = TableName;
            inValue.TableType = TableType;
            inValue.SqlString = SqlString;
            MES_Tablet_PC.ServiceReference1.Get_Table_DateResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).Get_Table_Date(inValue);
            return retVal.Get_Table_DateReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MES_Tablet_PC.ServiceReference1.getColumnStringResponse MES_Tablet_PC.ServiceReference1.RfEntry.getColumnString(MES_Tablet_PC.ServiceReference1.getColumnStringRequest request) {
            return base.Channel.getColumnString(request);
        }
        
        public string getColumnString(string sql) {
            MES_Tablet_PC.ServiceReference1.getColumnStringRequest inValue = new MES_Tablet_PC.ServiceReference1.getColumnStringRequest();
            inValue.sql = sql;
            MES_Tablet_PC.ServiceReference1.getColumnStringResponse retVal = ((MES_Tablet_PC.ServiceReference1.RfEntry)(this)).getColumnString(inValue);
            return retVal.getColumnStringReturn;
        }
    }
}
